### PR TITLE
Update method names to Three.js(r74)

### PR DESCRIPTION
**Pull request by neo**
Just wanted to get rid of all the Three.js warnings...
Changed all the removed/changed method names to the current ones instead, which is Three.js(r74).
Update the copyright year also, as a grunt side effect. XD

### CODE REVIEW

**Comment by neolwc** [comment]
@pehrlich what do you think?

**Comment by neo** [comment]
Closing as it's been a while and it still works with the current way

**Comment by pehrlich** [comment]
Ah sorry, didn't see!  Will take a look :)

**Comment by neo** [comment]
Don't worry about it! I assume it's safe to stay in that way, and no need to follow up the fast moving three.js updates which is r82 now. So I think it's fine to keep it as it is now.

**Comment by neolwc** [comment]
Or maybe just update the api names but not the version
=.

**Comment by pehrlich** [comment]
Merging this in.  Looks like it works out of the box with r82.  Note that this breaks compatibility for THREE.js < ~r74.  I think that's OK here as there's not too much else (anything?) going on in the release, so people can downgrade without loosing any fixes/features.

**Comment by neolwc** [comment]
Okay! Thanks, @pehrlich

**Pull request merged**
